# Generated by Django 3.0.3 on 2020-07-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerPlatters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price_small', models.DecimalField(decimal_places=2, help_text='Price in US dollars', max_digits=5)),
                ('price_large', models.DecimalField(decimal_places=2, help_text='Price in US dollars', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in US dollars', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Salads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in US dollars', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='SubExtras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in US dollars', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price_small', models.DecimalField(decimal_places=2, help_text='Price in US dollars', max_digits=4)),
                ('price_large', models.DecimalField(decimal_places=2, help_text='Price in US dollars', max_digits=4)),
                ('extras', models.ManyToManyField(blank=True, to='orders.SubExtras')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('style', models.CharField(choices=[('R', 'Regular'), ('S', 'Sicilian')], max_length=1)),
                ('price_small', models.DecimalField(decimal_places=2, help_text='Price in US dollars', max_digits=5)),
                ('price_large', models.DecimalField(decimal_places=2, help_text='Price in US dollars', max_digits=5)),
                ('toppings', models.ManyToManyField(blank=True, to='orders.Toppings')),
            ],
        ),
    ]
