# Generated by Django 3.0.3 on 2020-07-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('dishtype', models.CharField(max_length=32)),
                ('dishname', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in US dollars', max_digits=5)),
                ('remarks', models.TextField()),
                ('status', models.CharField(max_length=32)),
            ],
        ),
    ]
